name: Deployment
run-name: Deployment
on:
  push:
    branches: ['master']
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Docker Login
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Install QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Deploy
        run: |
          dotnet publish -c Release -r linux-arm -o ./build
          docker build --platform linux/arm/v7 . -t ghcr.io/badnickname/proxye/proxye:latest
          docker push ghcr.io/badnickname/proxye/proxye:latest
